ignore:
  - "src/main/java/nopointers/Main.java"
  - "src/main/java/nopointers/CLI.java"
  - "src/main/java/nopointers/Controller.java"
  - "src/main/java/nopointers/Connect.java"
  - "src/main/java/nopointers/NewPuzzleCommand.java"
  - "src/main/java/nopointers/Command.java"
  - "src/main/java/nopointers/CommandHistory.java"
  - "src/main/java/nopointers/AutoCompleter.java"
  - "src/main/java/nopointers/RankInfo.java"
  - "src/main/java/nopointers/GuessOutcome.java"

coverage:
  status:
    project:
      default:
        target: 0%
    patch:
      default:
        target: 0%
